#!/bin/sh

#SBATCH -N 1
#SBATCH -p GPU
#SBATCH --mail-type=ALL
#SBATCH --mail-user=addankn@sunyit.edu
#SBATCH --gres=gpu:k80:4
#SBATCH -t 22:10:00

#echo commands to stdout
set -x

module load tensorflow/1.5_gpu
module load keras/2.0.4

export TENSORFLOW_ENV=$TF_ENV

source $KERAS_ENV/bin/activate

#move to working directory
cd $HOME

cd Retinal-Segmentation

python python/create_model.py --cache

echo "ALL DONE!"
